name: nutmeg
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.6+97

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 2.0.0
  map_launcher: ^2.1.1
  font_awesome_flutter: 9.0.0
  flutter_signin_button: 2.0.0
  provider: any
  firebase_core: ^1.10.1
  firebase_auth: ^3.1.0
  google_sign_in: 5.0.4
  cloud_firestore: ^2.2.0
  date_time_picker: ^2.0.0
  http: ^0.13.3
  dio: ^4.0.0
  webview_flutter: ^2.0.8
  cool_alert: ^1.1.0
  week_of_year: ^2.0.0
  url_launcher: ^6.0.9
  carousel_slider: ^4.0.0
  readmore: ^2.1.0
  google_maps_flutter: ^2.0.6
  shimmer: ^2.0.0
  firebase_dynamic_links: ^2.0.9
  cloud_functions: 3.0.2
  firebase_crashlytics: ^2.0.0
  package_info_plus: ^1.0.2
  share_plus: ^2.1.4
  flutter_facebook_auth: 3.5.1
  firebase_messaging: ^11.1.0
  firebase_storage: ^10.0.3
  cached_network_image: ^3.1.0
  flutter_launcher_icons: ^0.9.2
  sign_in_with_apple: ^3.2.0
  device_info_plus: ^3.1.1
  pull_to_refresh: ^2.0.0
  flutter_svg: ^1.0.3
  transparent_image: ^2.0.0
  version: ^2.0.0
  tuple: ^2.0.0
  badges: ^2.0.2
  firebase_analytics: ^8.0.0
  firebase_performance: ^0.8.0+7
  get: ^4.6.1
  skeletons: ^0.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_remote_config: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/empty_state/
    - assets/launch/
    - assets/login/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  image_path_android: "assets/nutmeg.png"
  image_path_ios: "assets/nutmeg.png"
  android: true
  ios: true

