name: nutmeg
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.73+348

environment:
  sdk: 3.1.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  map_launcher: ^2.1.1
  font_awesome_flutter: 9.0.0
  flutter_signin_button: 2.0.0
  provider: any
  firebase_core: ^2.5.0
  firebase_auth: ^4.12.0
  google_sign_in: ^5.4.4
  cloud_firestore: ^4.4.0
#  date_time_picker: ^2.1.0
  http: ^1.1.0
  dio: ^4.0.0
  webview_flutter: ^4.0.7
  cool_alert: ^1.1.0
  week_of_year: ^2.0.0
  url_launcher: ^6.0.9
  carousel_slider: ^4.0.0
  readmore: ^2.1.0
  google_maps_flutter: ^2.0.6
  shimmer: ^2.0.0
  firebase_dynamic_links: ^5.0.12
  cloud_functions: ^4.0.8
  firebase_crashlytics: ^3.0.12
  package_info_plus: ^4.2.0
  share_plus: ^2.1.4
  flutter_facebook_auth: 6.0.2
  firebase_messaging: ^14.2.2
  firebase_storage: ^11.0.11
  cached_network_image: ^3.1.0
  flutter_launcher_icons: ^0.9.2
  sign_in_with_apple: ^5.0.0
  device_info_plus: ^9.1.0
  flutter_svg: ^2.0.5
  transparent_image: ^2.0.0
  version: ^2.0.0
  tuple: ^2.0.0
  badges: ^2.0.2
  firebase_analytics: ^10.1.1
  firebase_performance: ^0.9.0+11
  skeletons: ^0.0.3
  material_design_icons_flutter: ^5.0.6595
#  time_picker_widget: ^1.0.0+10
  image_picker: ^0.8.4+11
  image_cropper: ^5.0.0
  confetti: ^0.6.0
  shared_preferences: ^2.0.13
  logger: ^1.1.0
#  screenshot: ^1.2.3
#  charts_flutter: ^0.12.0
  dotted_border: ^2.0.0+2
  flutter_web_frame: ^0.0.3
  go_router: ^12.0.1
  universal_html: ^2.0.8
  google_places_flutter: ^2.0.6
  flutter_typeahead: ^4.3.1
  flutter_native_splash: ^2.2.9
  timezone: ^0.9.0
  decimal: ^2.3.2
  geolocator: ^9.0.2
  intl: ^0.18.1
  circle_flags: ^1.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_remote_config: ^4.3.2
  intl_translation: ^0.18.2
  data_table_2: ^2.3.3
  fl_chart: ^0.64.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  auto_translator: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/empty_state/
    - assets/launch/
    - assets/login/
    - assets/icons/
    - assets/sportcenters/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  image_path_android: "assets/nutmeg.png"
  image_path_ios: "assets/nutmeg.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#394BBB"
