default_platform(:ios)

bundle_identifier = "com.nutmegfootball.app"
app_id = ENV["APP_APPLE_ID"]
team_id = "CQD5MU7BCC"
username = "jirachi155@gmail.com"

platform :ios do
  lane :install_certificates do
      setup_ci(verbose: true)

      match(
        type: 'appstore',
        app_identifier: bundle_identifier,
        git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTH_TOKEN"]),
        readonly: true,
        verbose: true,
      )
  end

  lane :closed_beta do
#     setup_ci(verbose: true)
#
#     match(
#       type: 'appstore',
#       app_identifier: bundle_identifier,
#       git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTH_TOKEN"]),
#       readonly: true,
#       verbose: true,
#     )
#
#     gym(
#       scheme: "Runner",
#       export_method: "app-store",
#       export_team_id: team_id,
#       skip_build_archive: true,
#       archive_path: "../build/ios/archive/Runner.xcarchive",
#       verbose: true
#     )

    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: "./AuthKey_" + ENV["KEY_ID"] + ".p8",
    )

    pilot(
      api_key: api_key,
      apple_id: app_id,
      app_identifier: bundle_identifier,
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "../build/ios/ipa/Nutmeg.ipa",
      itc_provider: "CQD5MU7BCC"
    )
  end

  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: "./AuthKey_" + ENV["KEY_ID"] + ".p8",
    )

    deliver(
        api_key: api_key,
        app_identifier: bundle_identifier,
        ipa: "../build/ios/ipa/Nutmeg.ipa",
        submit_for_review: true,
        automatic_release: true,
        force: true,
        skip_metadata: true,
        skip_screenshots: true,
        run_precheck_before_submit: false,
        submission_information: { add_id_info_uses_idfa: false }
    )
  end

  lane :submit_for_review do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: "./AuthKey_" + ENV["KEY_ID"] + ".p8",
    )

    deliver(
        api_key: api_key,
        build_number: options[:build_number],
        app_version: options[:version],
        submit_for_review: true,
        automatic_release: true,
        force: true, # Skip HTML report verification
        skip_app_version_update: true,
        skip_metadata: true,
        skip_screenshots: true,
        skip_binary_upload: true,
        run_precheck_before_submit: false,
        app_identifier: bundle_identifier,
        submission_information: { add_id_info_uses_idfa: false }
    )
  end
end
