default_platform(:android)

platform :android do

  lane :build do
    sh("cd ../.. && flutter build appbundle --release --dart-define-from-file=.env.prod")
  end

  lane :playstoreInternalTest do
    build
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "internal",
    )
  end

  lane :playstoreProduction do
    build
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "production",
      release_status: "completed",
    )
  end

  lane :promoteToProduction do
    upload_to_play_store(
      track: "internal",
      track_promote_to: "production",
      release_status: "completed",
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end
