// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlU4z5DbXqoafB-T-t2mJ8rGv3Y4rAcWY',
    appId: '1:956073807168:web:e8f41b530ab699a8a6fea5',
    messagingSenderId: '956073807168',
    projectId: 'nutmeg-9099c',
    authDomain: 'nutmeg-9099c.firebaseapp.com',
    databaseURL: 'https://nutmeg-9099c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nutmeg-9099c.appspot.com',
    measurementId: 'G-2EQWC6Y0S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjyxMFOrglJXpK6QlzJR_Mh8hNH3NcGS0',
    appId: '1:956073807168:android:6da9954e5c9bb9ffa6fea5',
    messagingSenderId: '956073807168',
    projectId: 'nutmeg-9099c',
    databaseURL: 'https://nutmeg-9099c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nutmeg-9099c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfYYeH1-57PAeasukpaajWq3cR0sGO9qY',
    appId: '1:956073807168:ios:25818a16a5ea2cd2a6fea5',
    messagingSenderId: '956073807168',
    projectId: 'nutmeg-9099c',
    databaseURL: 'https://nutmeg-9099c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nutmeg-9099c.appspot.com',
    androidClientId: '956073807168-0k19bq5mee448tc61qvfk6e1e9psjke4.apps.googleusercontent.com',
    iosClientId: '956073807168-4gia0lo6ggju7f1kiin9j2ibn3q5b9qd.apps.googleusercontent.com',
    iosBundleId: 'com.nutmeg.app',
  );
}
