default_platform(:ios)

bundle_identifier = "com.nutmeg.app"
app_id = "1592985083"
team_id = "CN7XB83K76"
username = "alessandroliparoti@live.it"

platform :ios do
  lane :install_certificates do
      setup_ci(verbose: true)

      match(
        type: 'appstore',
        app_identifier: bundle_identifier,
        git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTH_TOKEN"]),
        readonly: true,
        verbose: true,
      )
  end

  lane :closed_beta do
    gym(
      scheme: "Runner",
      export_method: "app-store",
      export_team_id: team_id,
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
      verbose: true
    )

    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: "549abdc6-6a6f-40f5-b041-c46daa9d6c91",
      key_filepath: "./AuthKey_" + ENV["KEY_ID"] + ".p8",
    )

    pilot(
      api_key: api_key,
      apple_id: app_id,
      app_identifier: bundle_identifier,
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./Runner.ipa",
      itc_provider: "CN7XB83K76"
    )
  end

  lane :submit_for_review do |options|
    deliver(
        build_number: options[:build_number],
        app_version: options[:version],
        submit_for_review: true,
        automatic_release: true,
        force: true, # Skip HTMl report verification
        skip_app_version_update: false,
        skip_metadata: false,
        skip_screenshots: true,
        skip_binary_upload: true,
        run_precheck_before_submit: false,
        username: username,
        app_identifier: bundle_identifier,
        submission_information: { add_id_info_uses_idfa: false }
    )
  end
end
