# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to TestFlight"
  lane :testflight do
    get_certificates
    get_provisioning_profile
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end

  desc "Push a new release build to the App Store"
  lane :release do
    app_store_connect_api_key(
      key_id: "CTJDHGWL48",
      issuer_id: "549abdc6-6a6f-40f5-b041-c46daa9d6c91",
      key_content: ENV['APPCONNECT_KEY']
    )
    get_certificates
    get_provisioning_profile
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end
end
