default_platform(:ios)

bundle_identifier = "com.nutmeg.app"
app_id = "1592985083"
team_id = "CN7XB83K76"

platform :ios do
  lane :sign_ipa do
    setup_ci(verbose: true)

    match(
      type: 'appstore',
      app_identifier: bundle_identifier,
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTH_TOKEN"]),
      readonly: true,
      verbose: true,
    )

    gym(
      scheme: "Runner",
      export_method: "app-store",
      export_team_id: team_id,
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
      verbose: true
    )
  end

  lane :closed_beta do
      sign_ipa

      pilot(
        apple_id: app_id,
        app_identifier: bundle_identifier,
        skip_waiting_for_build_processing: true,
        skip_submission: true,
        distribute_external: false,
        notify_external_testers: false,
        ipa: "./Runner.ipa",
        itc_provider: team_id
      )
  end

  lane :submit_for_review do |options|
    deliver(
        build_number: options[:build_number],
        app_version: options[:version],
        submit_for_review: true,
        automatic_release: true,
        force: true, # Skip HTMl report verification
        skip_app_version_update: false,
        skip_metadata: false,
        skip_screenshots: true,
        skip_binary_upload: true,
        run_precheck_before_submit: false,
        username: "alessandroliparoti@live.it",
        app_identifier: bundle_identifier,
        submission_information: { add_id_info_uses_idfa: false }
    )
  end
end
