name: Playstore Deployment

on:
  push:
    tags:
      - v*

jobs:
  deploy_android:
    name: Deploy build to Playstore (internal test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: echo $NUTMEG_DEPLOY_KEY  | base64 -d > android/nutmeg-deploy-key.json
        env:
          NUTMEG_DEPLOY_KEY: ${{ secrets.NUTMEG_DEPLOY_KEY }}
      - run: echo $ANDROID_JSON | base64 -d > android/nutmeg-9099c-sa-credentials.json
        env:
          ANDROID_JSON: ${{ secrets.ANDROID_JSON }}
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.9'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build appbundle -t lib/screens/Launch.dart --release
      - name: Deploy to Playstore production
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: playstoreInternalTest
          subdirectory: android