name: Cloud Functions Deploy

on:
  push:
    branches:
      - master
    paths:
      - "functions/**"
      - "firebase.json"
      - ".firebaserc"

jobs:
  deploy_functions:
    name: Deploy Cloud Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Deploy to Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NUTMEG_9099C }}"
          PROJECT_PATH: .
