name: Cloud Functions Deploy

on:
  push:
    branches:
      - master
    paths:
      - "functions/**"
      - "firebase.json"
      - ".firebaserc"

jobs:
  deploy_functions:
    name: Deploy Cloud Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Prepare Python virtual environment
        working-directory: functions
        run: |
          python -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt

      - name: Deploy to Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NUTMEG_9099C }}"
          PROJECT_PATH: .
