name: Cloud Functions Deploy

on:
  push:
    branches:
      - master
    paths:
      - "functions/**"
      - "firebase.json"
      - ".firebaserc"

jobs:
  deploy_functions:
    name: Deploy Cloud Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Prepare Python virtual environment
        working-directory: functions
        run: |
          python -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NUTMEG_9099C }}"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Functions
        run: |
          . functions/venv/bin/activate
          firebase deploy --only functions --project nutmeg-9099c --force
