name: Appstore Deployment

on:
  push:
    tags:
      - v*

jobs:
  deploy_ios:
    name: Deploy build to TestFlight
    runs-on: macOS-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: pwd; echo $P8_KEY | base64 -d > ios/AuthKey_CTJDHGWL48.p8
        env:
          P8_KEY: ${{ secrets.P8_KEY }}
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.1'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign -t lib/screens/Launch.dart
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: 'ios'
      - uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'closed_beta'
          subdirectory: 'ios'
        env:
          APPLICATION_ID: "1592985083"
          BUNDLE_IDENTIFIER: "com.nutmeg.app"
          DEVELOPER_PORTAL_TEAM_ID: "CN7XB83K76"
          FASTLANE_APPLE_ID: "alessandroliparoti@live.it"
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: "odnv-ruvg-mzoo-enld"
          MATCH_PASSWORD: "nutmeg"
          GIT_AUTH_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
      - name: save artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: save-log-file
          path: /Users/runner/Library/Logs/gym/Runner-Runner.log
      - name: log certificates after
        if: always()
        run: security find-certificate
      - name: log identities after
        if: always()
        run: security find-identity