name: Appstore Deployment

on:
  push

jobs:
  build_ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: pwd; echo $P8_KEY | base64 -d > ios/AuthKey_CTJDHGWL48.p8
        env:
          P8_KEY: ${{ secrets.P8_KEY }}
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.2'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign -t lib/screens/Launch.dart
