name: iOS Build

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"

jobs:
  build_ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: pwd; echo $P8_KEY | base64 -d > ios/AuthKey_CTJDHGWL48.p8
        env:
          P8_KEY: ${{ secrets.P8_KEY }}
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.1'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build ipa --verbose --release --no-codesign -t lib/screens/Launch.dart
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: save-ipa
          path: |
            build/ios/ipa/*
              
