on: push
name: compile
jobs:
  build:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
      - run: flutter pub get
      - run: flutter run -t lib/screens/Launch.dart
