on: push
name: cleans, build and test app (mobile - android)
jobs:
  build:
    name: build-test-and-apk
    runs-on: ubuntu-latest
    steps:
      - run: ls -l
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      # - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      # - run: flutter analyze .

      # Run widget tests for our flutter project.
      # - run: flutter test

      # Build apk.
      - run: flutter build appbundle -t lib/screens/Launch.dart

      - name: Deploy to playstore internal testing
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: internalAppSharing
          subdirectory: android

      # Upload generated apk to the artifacts.
#      - uses: actions/upload-artifact@v1
#        with:
#          name: release-apk
#          path: build/app/outputs/apk/release/app-release.apk