name: Web Build

on:
  push:
    branches:
      - master

jobs:
  build_ios:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.1'
      - run: flutter build web -t lib/screens/Launch.dart --release
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy master
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NUTMEG_9099C }}'
