name: Web Build

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"

jobs:
  build_ios:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.2'
      - run: flutter build web -t lib/screens/Launch.dart
