name: Web Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_ios:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
      - run: flutter build web -t lib/screens/Launch.dart --release --no-sound-null-safety --web-renderer=canvaskit
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NUTMEG_9099C }}'
