name: Web Build

on:
  push:
    branches:
      - master

jobs:
  build_ios:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.2'
      - run: flutter build web -t lib/screens/Launch.dart
      - run: cat firebase.json
      - run: ls build/web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GIT_AUTH_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NUTMEG_9099C }}'
          projectId: nutmeg-9099c
          channelId: master
